name: CI

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 12
    - run: |
        yarn install
        yarn test
        yarn build

  package:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 12
    - run: |
        yarn install
        yarn dist:linux

  update-release-draft:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
