name: CI

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 12
    - run: |
        yarn install
        yarn build
        yarn test

  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add-artifacts-to-release: 
    needs: [update-release-draft]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SKIP_PREFLIGHT_CHECK: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 12
    - run: |
        yarn install
        yarn dist:linux

  # 'ci' check is required for mergeability, wait for other jobs
  ci:
    needs: 
      - build-and-test
      - update-release-draft
      - add-artifacts-to-release
    runs-on: ubuntu-latest
    steps:
      - run: echo CI checks complete